[[redirects]]
  from = "/*"
  to = "/pageiserror.html"
  status = 404
  force = true

[[redirects]]
  from = "/sitearchive/2018/*"
  to = "https://2018.housemoonsprinter.co.uk"
  status = 301
  force = true